version: '3'

services:
  cas:
    image: apereo/cas:6.6.13
    container_name: cas-server
    ports:
      - "8443:8443"
      - "5555:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=standalone
      - SERVER_PORT=8080
      - LOGGING_LEVEL_ORG_APEREO_CAS=DEBUG
      - CAS_SERVER_NAME=http://localhost:5555
      - CAS_SERVER_PREFIX=http://localhost:5555/cas
      # 启用 HTTP（仅用于测试）
      - CAS_TGCOOKIE_SECURE=false
      - CAS_WARNING_COOKIE_SECURE=false
      # 内置用户（用于测试）
      - CAS_AUTHN_ACCEPT_USERS=casuser::Mellon,admin::admin123,zhangsan::123456,lisi::654321
      # 设置字符编码
      - JAVA_OPTS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./config:/etc/cas/config
      - ./services:/etc/cas/services
    networks:
      - cas-network

networks:
  cas-network:
    driver: bridge