# 敏感数据扫描服务器配置示例

# 基本配置
display_name: "敏感数据扫描服务器"
port: 3008

# 文档存储路径
document_storage_path: "/tmp/documents/uploads"

# 扫描结果输出目录
visualization_output_dir: "/tmp/scan_visualizations"

# LangExtract 配置
langextract_model: "Qwen/Qwen3-30B-A3B-Instruct-2507"
langextract_api_key: "${SILICONFLOW_API_KEY}"  # 从环境变量读取
langextract_base_url: "https://api.siliconflow.cn/v1"
langextract_max_workers: 1  # 并发扫描的最大工作线程数
langextract_max_char_buffer: 50000  # 单次推理的最大字符数

# 任务管理配置
max_concurrent_tasks: 10  # 最大并发任务数

# 数据库配置（可选，如果不配置将使用内存存储）
# 如果backend已经配置了数据库，MCP服务器会自动使用相同的数据库配置
# 无需在这里重复配置