# CAS 配置文件 - YAML格式（支持UTF-8）

# 禁用SSL（仅用于测试）
server:
  ssl:
    enabled: false
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# CAS认证属性配置
cas:
  authn:
    attribute-repository:
      stub:
        attributes:
          zhangsan:
            display_name: 张三
            email: zhangsan@taobao.com
            group_name: CN=张三,OU=开发组,OU=技术部,OU=淘宝,DC=taobao,DC=COM
            username: zhangsan
          admin:
            display_name: 管理员
            email: admin@taobao.com
            group_name: CN=管理员,OU=运维组,OU=技术部,OU=淘宝,DC=taobao,DC=COM
            username: admin
          lisi:
            display_name: 李四
            email: lisi@taobao.com
            group_name: CN=李四,OU=测试组,OU=技术部,OU=淘宝,DC=taobao,DC=COM
            username: lisi