# MCP服务器配置文件
servers:
  database_server:
    script: "servers/db_mcp_server.py"
    port: 3001
    name: "数据库工具服务器(MySQL)"
    description: "提供MySQL数据库相关工具"
    health_endpoint: "/health"
    
  ssh_server:
    script: "servers/ssh_mcp_server.py"
    port: 3002
    name: "SSH工具服务器"
    description: "提供SSH远程系统管理工具"
    health_endpoint: "/health"
    
  elasticsearch_server:
    script: "servers/es_mcp_server.py"
    port: 3003
    name: "Elasticsearch工具服务器"
    description: "提供Elasticsearch查询和分析工具"
    health_endpoint: "/health"
    
  zabbix_server:
    script: "servers/zabbix_mcp_server.py"
    port: 3004
    name: "Zabbix工具服务器"
    description: "提供Zabbix监控数据获取工具"
    health_endpoint: "/health"

# 环境配置
environment:
  python_env: "py312"  # conda环境名称
  log_level: "INFO"
  
# 目录配置
directories:
  logs: "logs"
  pids: "pids"
  servers: "servers"
  scripts: "scripts"