# MCP服务器配置文件
# 新格式：所有配置集中管理

servers:
  db_query:
    enabled: false
    script: "servers/db_query/runserver.py"
    display_name: "数据库查询服务"
    config:
      port: 3001
      api_base_url: "http://172.20.10.2:8111"
      api_token: "app-tbCzKza1riIJ6M3Grn4nWSQa"
      
  ssh_exec:
    enabled: false
    script: "servers/ssh_exec/runserver.py"
    display_name: "SSH远程连接服务"
    config:
      port: 3002
      host: 82.156.146.51
      ssh_port: 22
      configs:
        - username: root
          password: "123456"
        - username: gaochao
          key_file: "/Users/gaochao/.ssh/id_rsa"
          
  es_search:
    enabled: false
    script: "servers/es_search/runserver.py"
    display_name: "Elasticsearch搜索服务"
    config:
      port: 3003
      protocol: "http"
      host: "82.156.146.51"
      es_port: 9200
      timeout: 30
      username: ""
      password: ""
      verify_ssl: false
      
  zabbix_monitor:
    enabled: true
    script: "servers/zabbix_monitor/runserver.py"
    display_name: "Zabbix监控服务"
    config:
      port: 3004
      url: "http://82.156.146.51:8080/zabbix/api_jsonrpc.php"
      username: "Admin"
      password: "zabbix"
      
  sop_server:
    enabled: true
    script: "servers/sop_server/runserver.py"
    display_name: "SOP标准操作程序服务"
    config:
      port: 3005
      db_host: 82.156.146.51
      db_port: 3306
      db_username: gaochao
      db_password: "fffjjj"
      db_database: omind  # SOP数据库名称
      
  chart_server:
    enabled: true
    script: "servers/chart_server/runserver.py"
    display_name: "图表可视化服务"
    config:
      port: 3007
      # 图表样式配置
      default_style: "seaborn"
      default_dpi: 100
      # 支持的图表类型
      supported_charts:
        - line
        - bar
        - pie
        - scatter
        - heatmap
        - multi_series
        
  echarts_server:
    enabled: true
    script: "servers/echarts_server/runserver.py"
    display_name: "交互式图表服务"
    config:
      port: 3008