# MCP服务器配置文件
# 新格式：所有配置集中管理

servers:
  db_query:
    enabled: true
    port: 3001
    script: "servers/db_mcp_server.py"
    display_name: "MySQL数据库服务"
    config:
      host: 82.156.146.51
      port: 3306
      username: gaochao
      password: "fffjjj"
      database: information_schema
      
  ssh_exec:
    enabled: true
    port: 3002
    script: "servers/ssh_mcp_server.py"
    display_name: "SSH远程连接服务"
    config:
      host: 82.156.146.51
      port: 22
      configs:
        - username: root
          password: "123456"
        - username: gaochao
          key_file: "/Users/gaochao/.ssh/id_rsa"
          
  es_search:
    enabled: true
    port: 3003
    script: "servers/es_mcp_server.py"
    display_name: "Elasticsearch搜索服务"
    config:
      protocol: "http"
      host: "82.156.146.51"
      port: 9200
      timeout: 30
      username: ""
      password: ""
      verify_ssl: false
      
  zabbix_monitor:
    enabled: true
    port: 3004
    script: "servers/zabbix_mcp_server.py"
    display_name: "Zabbix监控服务"
    config:
      url: "http://82.156.146.51:60080"
      username: "Admin"
      password: "zabbix"
      
  sop_server:
    enabled: true
    port: 3005
    script: "servers/sop_mcp_server.py"
    display_name: "SOP标准操作程序服务"
    config:
      host: 82.156.146.51
      port: 3306
      username: gaochao
      password: "fffjjj"
      database: omind  # SOP数据库名称
      
  document_server:
    enabled: true
    port: 3006
    script: "servers/document_mcp_server.py"
    display_name: "文档生成服务"
    config:
      document_dir: "/tmp/mcp_documents"