# MCP服务器配置文件
# 新格式：所有配置集中管理

servers:
  db_query:
    enabled: false
    script: "servers/db_query/runserver.py"
    display_name: "数据库查询服务"
    config:
      port: 3001
      api_base_url: "http://172.20.10.2:8111"
      api_token: "app-tbCzKza1riIJ6M3Grn4nWSQa"
      
  ssh_exec:
    enabled: false
    script: "servers/ssh_exec/runserver.py"
    display_name: "SSH远程连接服务"
    config:
      port: 3002
      host: 82.156.146.51
      ssh_port: 22
      configs:
        - username: root
          password: "123456"
        - username: gaochao
          key_file: "/Users/gaochao/.ssh/id_rsa"
          
  es_search:
    enabled: false
    script: "servers/es_search/runserver.py"
    display_name: "Elasticsearch搜索服务"
    config:
      port: 3003
      protocol: "http"
      host: "82.156.146.51"
      es_port: 9200
      timeout: 30
      username: ""
      password: ""
      verify_ssl: false
      
  zabbix_monitor:
    enabled: true
    script: "servers/zabbix_monitor/runserver.py"
    display_name: "Zabbix监控服务"
    config:
      port: 3004
      url: "http://82.156.146.51:8080/zabbix/api_jsonrpc.php"
      username: "Admin"
      password: "zabbix"
      
  sop_server:
    enabled: false
    script: "servers/sop_server/runserver.py"
    display_name: "SOP标准操作程序服务"
    config:
      port: 3005
      host: 82.156.146.51
      db_port: 3306
      username: gaochao
      password: "fffjjj"
      database: omind  # SOP数据库名称
      
  document_server:
    enabled: true
    script: "servers/document_server/runserver.py"
    display_name: "文档生成服务"
    config:
      port: 3006
      document_dir: "/tmp/mcp_documents"
      
  sensitive_scan_server:
    enabled: true
    script: "servers/sensitive_scan_server/runserver.py"
    display_name: "敏感数据扫描服务"
    config:
      port: 3007
      document_storage_path: "/tmp/documents/uploads"  # 文档存储路径
      llm_api_base: "https://api.siliconflow.cn/v1"
      llm_api_key: "sk-dldltbdokxccwaqhjvpvjuvznimwztmfvpxpikypeysftktm" 
      llm_model: "Qwen/Qwen3-30B-A3B-Instruct-2507"
      chunk_size: 10000  # 扫描分块大小（字符数），默认10000
      file_concurrency: 3  # 文件并发度（同时扫描的文件数），默认3
      
  sensitive_scan_server_v2:
    enabled: true  # 启用 V2 版本
    script: "servers/sensitive_scan_server_v2/runserver.py"
    display_name: "敏感数据扫描服务V2(LangExtract)"
    config:
      port: 3008
      document_storage_path: "/tmp/documents/uploads"  # 文档存储路径
      # LangExtract 配置
      langextract_provider: "custom"  # 提供商: gemini, openai, custom
      langextract_model: "Qwen/QwQ-32B"  # 模型ID
      langextract_api_key: "sk-dldltbdokxccwaqhjvpvjuvznimwztmfvpxpikypeysftktm"
      langextract_base_url: "https://api.siliconflow.cn/v1"  # SiliconFlow API地址
      visualization_output_dir: "/tmp/scan_visualizations"  # 可视化报告输出目录
      # 扫描配置
      chunk_size: 10000  # 扫描分块大小（字符数），默认10000
      file_concurrency: 3  # 文件并发度（同时扫描的文件数），默认3