/**
 * 默认菜单数据
 * 基于你的 rbac_menus 表结构，适配当前智能运维平台的菜单
 */

import { MenuInfo } from '../types/menu';

export const defaultMenusData: MenuInfo[] = [
  // 一级菜单：用户服务
  {
    id: 1,
    menu_id: 1,
    menu_name: '用户服务',
    menu_icon: 'CustomerServiceOutlined',
    parent_id: 0,
    route_path: '/user-service',
    redirect_path: '/service/agents',
    menu_component: '',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  // 用户服务下的子菜单
  {
    id: 2,
    menu_id: 2,
    menu_name: '智能体广场',
    menu_icon: 'AppstoreOutlined',
    parent_id: 1,
    route_path: '/service/agents',
    redirect_path: '',
    menu_component: 'AgentMarketplace',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },
  
  {
    id: 3,
    menu_id: 3,
    menu_name: '知识中心',
    menu_icon: 'BookOutlined',
    parent_id: 1,
    route_path: '/service/knowledge',
    redirect_path: '',
    menu_component: 'KnowledgeManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  // 一级菜单：系统管理
  {
    id: 4,
    menu_id: 4,
    menu_name: '系统管理',
    menu_icon: 'SettingOutlined',
    parent_id: 0,
    route_path: '/system',
    redirect_path: '/system/agents',
    menu_component: '',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  // 系统管理下的子菜单
  {
    id: 5,
    menu_id: 5,
    menu_name: '智能体管理',
    menu_icon: 'UserOutlined',
    parent_id: 4,
    route_path: '/system/agents',
    redirect_path: '',
    menu_component: 'AgentManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 6,
    menu_id: 6,
    menu_name: 'SOP管理',
    menu_icon: 'FileTextOutlined',
    parent_id: 4,
    route_path: '/system/sop',
    redirect_path: '',
    menu_component: 'SOPManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 7,
    menu_id: 7,
    menu_name: 'MCP管理',
    menu_icon: 'LinkOutlined',
    parent_id: 4,
    route_path: '/system/mcp',
    redirect_path: '',
    menu_component: 'MCPManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 8,
    menu_id: 8,
    menu_name: '模型管理',
    menu_icon: 'ApiOutlined',
    parent_id: 4,
    route_path: '/system/models',
    redirect_path: '',
    menu_component: 'ModelsManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 9,
    menu_id: 9,
    menu_name: '任务管理',
    menu_icon: 'ClockCircleOutlined',
    parent_id: 4,
    route_path: '/system/tasks',
    redirect_path: '',
    menu_component: 'TasksManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  // 基于你的数据库，可以继续添加其他菜单
  // 比如：用户管理、角色管理、权限管理等
  {
    id: 10,
    menu_id: 10,
    menu_name: '用户管理',
    menu_icon: 'TeamOutlined',
    parent_id: 4,
    route_path: '/system/user',
    redirect_path: '',
    menu_component: 'UserManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 11,
    menu_id: 11,
    menu_name: '角色管理',
    menu_icon: 'SafetyCertificateOutlined',
    parent_id: 4,
    route_path: '/system/userRole',
    redirect_path: '',
    menu_component: 'RoleManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 12,
    menu_id: 12,
    menu_name: '权限管理',
    menu_icon: 'KeyOutlined',
    parent_id: 4,
    route_path: '/system/permission',
    redirect_path: '',
    menu_component: 'PermissionManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 13,
    menu_id: 13,
    menu_name: '租户管理',
    menu_icon: 'BuildingOutlined',
    parent_id: 4,
    route_path: '/system/tenant',
    redirect_path: '',
    menu_component: 'TenantManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },

  {
    id: 14,
    menu_id: 14,
    menu_name: '菜单管理',
    menu_icon: 'MenuOutlined',
    parent_id: 4,
    route_path: '/menu',
    redirect_path: '',
    menu_component: 'MenuManagement',
    show_menu: 1,
    create_time: new Date().toISOString(),
    update_time: new Date().toISOString(),
    create_by: 'system',
    update_by: 'system',
  },
];